project_id = "cvgdxmmtrukahyvkgazj"

[functions.send-service-reminders]
verify_jwt = false

[functions.send-fill-in-notifications]
verify_jwt = true

[functions.send-service-comment-notifications]
verify_jwt = true

[functions.send-fill-in-accepted-notification]
verify_jwt = true
